version: '3'

services:
  aws-glue-local-interpreter:
    image: "anthonypernia/aws-glue-local-interpreter"
    volumes:
      - ~/.aws:/root/.aws
      - ~/aws-glue-developments:/root/developments #(OPTIONAL)
    ports:
      - "8888:8888"
    restart: always
