on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: remove old image
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      -
        name: create image buildx
        run: docker buildx create --name multiarch --driver docker-container --use
      -
        name: inspect image buildx
        run: docker buildx inspect --bootstrap
      -
        name: build image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t  $GITHUB_REPOSITORY:latest --push .
        

